#External
#include: 'http://server-dev/.amazing-script.yml'
#Within the repository
#include: "/templates/.amazing-script.yml"

stages:
   - preamble
   - build
   - deploy

# WARNING: Remember to change the TAG based on the branch: master -> stable, develop -> latest, any-other-branch -> latest
variables:
   TAG: stable
   VERSION_BASED_ON_GIT_TAG: "true"

before_script:
    - source /root/dls_gitlab_ci/gitlab-script.sh

preamble:
  image: server-dev:5000/dls-dev:$TAG
  stage: preamble
  script:
    - source /root/dls_gitlab_ci/gitlab-preamble.sh
  artifacts:
    paths:
      - version
      - release

build-and-test:
  image: server-dev:5000/dls-dev:$TAG
  stage: build
  script:
    - source /root/dls_gitlab_ci/gitlab-ci.bash
    - source /opt/ros/dls-distro/setup.bash
    - catkin_make -DCMAKE_BUILD_TYPE=Debug && catkin_make run_tests && catkin_make test

deploy:
  image: server-dev:5000/dls-dev:$TAG
  stage: deploy
  script:
    - source /root/dls_gitlab_ci/gitlab-deployment.sh
    - curl -X POST -F token=$DLS_DISTRO_TOKEN -F ref=$CI_COMMIT_REF_NAME -F variables[SUBMODULE_COMMIT_MSG]="$CI_COMMIT_MESSAGE" -F variables[SUBMODULE_COMMIT_SHA]=$CI_COMMIT_SHA -F variables[SUBMODULE]=$CI_PROJECT_NAME https://gitlab.advr.iit.it/api/v4/projects/43/trigger/pipeline
  only:
  - master
  - develop

