hyq:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000
    
    leg_controller:
      type: legged_controllers/LegController
      joints:
        - lf_haa_joint
        - lf_hfe_joint
        - lf_kfe_joint

        - rf_haa_joint
        - rf_hfe_joint
        - rf_kfe_joint

        - lh_haa_joint
        - lh_hfe_joint
        - lh_kfe_joint

        - rh_haa_joint
        - rh_hfe_joint
        - rh_kfe_joint
      gains:
        lf_haa_joint: {p: 300.0, d: 50.0}
        lf_hfe_joint: {p: 100.0, d: 20.0}
        lf_kfe_joint: {p: 500.0, d: 20.0}

        rf_haa_joint: {p: 300.0, d: 50.0}
        rf_kfe_joint: {p: 100.0, d: 20.0}
        rf_hfe_joint: {p: 100.0, d: 20.0}

        lh_haa_joint: {p: 300.0, d: 50.0}
        lh_hfe_joint: {p: 100.0, d: 20.0}
        lh_kfe_joint: {p: 100.0, d: 20.0}

        rh_haa_joint: {p: 300.0, d: 50.0}
        rh_kfe_joint: {p: 100.0, d: 20.0}
        rh_hfe_joint: {p: 100.0, d: 20.0}